apiVersion: v1
kind: Service
metadata:
  name: eks-demo
spec:
  type: LoadBalancer
  selector:
    service: eks-demo
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
  labels:
    name: eks-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eks-demo
  template:
    metadata:
      labels:
        service: eks-demo
    spec:
      containers:
      - name: eks-demo
        image: 813964244258.dkr.ecr.us-east-1.amazonaws.com/eks-demo:1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: eks-demo-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpassword-secret
              key: DB_PASSWORD
      restartPolicy: Always